apiVersion: v1
kind: Secret
metadata:
  name: service-account-credentials
type: Opaque
data:
  sa_json: ""

#kubectl create secret generic service-account-credentials --from-file=sa_json=D:\EngDados\gcp\sa_credentials.json -n processing
